name: flutterradiolisteningglobalradios
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  just_audio: ^0.9.39
  cached_network_image: ^3.3.1
  volume_controller: ^2.0.7
  google_fonts: ^6.1.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
